### ISSUE TITLE
path_prefix ?

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#30]
To reach the optimal files layout, I keep modifying 3 `path`s for each CI.  All of them have the same prefix.  So I wonder if we could define common prefix separately, so instead of 
```yaml
repo: datalad/datalad
ci:
  github:
    path: '{year}/{month}//{day}/{type}/{type_id}/{commit[:8]}/{ci}-{wf_name}/{number}-{common_status}/'
  travis:
    path: '{year}/{month}//{day}/{type}/{type_id}/{commit[:8]}/{ci}-{number}-{common_status}/{job}.txt'
  appveyor:
    path: '{year}/{month}//{day}/{type}/{type_id}/{commit[:8]}/{ci}-{number}-{common_status}/{job}.txt'
```

it would be

```yaml
repo: datalad/datalad
path_prefix: '{year}/{month}//{day}/{type}/{type_id}/{commit[:8]}/'
ci:
  github:
    path: '{ci}-{wf_name}/{number}-{common_status}/'
  travis:
    path: '{ci}-{number}-{common_status}/{job}.txt'
  appveyor:
    path: '{ci}-{number}-{common_status}/{job}.txt'
```
or smth like that?
