### ISSUE TITLE
generalize `{path_prefix}` into `vars:` (or `consts:` or anything better)

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#43]
Instead of providing some ad-hoc treatment to path, and to provide more flexibility in reuse etc, lets RF

```
path_prefix: '{year}/{month}/{day}/{ci}/{type}/{type_id}/{commit}/'
ci:
  github:
    path: '{wf_name}/{number}/'
```
into a more explicit but also more flexible:
```
vars:
  path_prefix: '{year}/{month}/{day}/{ci}/{type}/{type_id}/{commit}'
ci:
  github:
    path: '{path_prefix}/{wf_name}/{number}/'
```
so we could add any additional variable and possibly different `path_prefix2` to use where desired.
