### ISSUE TITLE
leads to 500

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#54]
tried after merging #53  on
```yaml
repo: datalad/datalad
vars:
  path_prefix: '{year}//{month}//{day}/{type}/{type_id}/{abbrev_commit}/{ci}-'
ci:
  github:
    path: '{path_prefix}{wf_name}-{number}-{common_status}/'
  travis:
    path: '{path_prefix}{number}-{common_status}/{job}.txt'
  appveyor:
    path: '{path_prefix}{number}-{common_status}/{job}.txt'
    accountName: mih
    projectSlug: datalad
since: 2021-05-24T00:00:00Z
types: [cron, pr, push]
#secrets:
  #github: '\b(v1\.)?[a-f0-9]{40}\b'
  #docker-hub: '\b[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}\b'
  #appveyor: '\b(v2\.)?[a-z0-9]{20}\b'
  #travis: '\b[a-zA-Z0-9]{22}\b'
  #aws: '\b[a-zA-Z0-9+/]{40}\b'
datalad:
  enabled: true
  cfg_proc: text2git

```

and got (with limits printed after -- none is hit):

```
2021-05-24T11:19:05-0400 [INFO    ] tinuous Downloading logs for job 11955.6 to 2021/05/24/pr/5693/5a27faf/travis-11955-success/6.txt
Traceback (most recent call last):
  File "/home/datalad/miniconda3/envs/tinuous-dev/bin/tinuous", line 33, in <module>
    sys.exit(load_entry_point('tinuous', 'console_scripts', 'tinuous')())
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 1016, in fetch
    paths = obj.download(Path(path))
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 682, in download
    r = self.client.get(f"/job/{self.job_id}/log.txt", stream=True)
  File "/mnt/datasets/datalad/ci/tinuous/src/tinuous/__main__.py", line 572, in get
    r.raise_for_status()
  File "/home/datalad/miniconda3/envs/tinuous-dev/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.travis-ci.com/job/507427442/log.txt
{ 
  "resources": {
    "core": {
      "limit": 5000,
      "used": 53,
      "remaining": 4947,
      "reset": 1621871809
    },
    "search": {
      "limit": 30,
      "used": 1,
      "remaining": 29,
      "reset": 1621869590
    },
    "graphql": {
      "limit": 5000,
      "used": 3,
      "remaining": 4997,
      "reset": 1621870273
    },
    "integration_manifest": {
      "limit": 5000,
      "used": 0,
      "remaining": 5000,
      "reset": 1621873146
    },
    "source_import": {
      "limit": 100,
      "used": 0,
      "remaining": 100,
      "reset": 1621869606
    },
    "code_scanning_upload": {
      "limit": 500,
      "used": 0,
      "remaining": 500,
      "reset": 1621873146
    }
  },
  "rate": {
    "limit": 5000,
    "used": 53,
    "remaining": 4947,
    "reset": 1621871809
  }
}

```
