### ISSUE TITLE
Be able to provide different settings (paths) for different types (cron, pr, push) of builds

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#83]
I do not have yet a good idea on how we should enable that.  Probably some way to establish conditionals for values, e.g.
```
path[type=pr]: {common}/{type}-{type_id}
path[type=cron]: {common}/{type_id}
```
or probably cleaner to make `types: [cron, pr, push]` into
```
types:
  cron: 
    ci: ... and all what could be specified there
  pr:
   ...
  push:
   ...
```
or alike (cons: might lead to needing to duplicate, in particular when e.g. both pr and push could have the same config).

But kept thinking that flexibility is desired while test driving it on datalad/git-annex where most of the jobs are cron, and we do not care about `{build_commit}` since it doesn't correspond to commit in git-annex anyways and nearly always the same (unless we add a patch etc), as we would care for a PR.
